name: Build and deploy Hugo site to Azure Web App - blogualhmisEq05

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build Hugo site
        run: hugo

      - name: Zip public directory
        run: zip -r release.zip public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-site

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DA1EC74B6A44DB5AA9CAC47FE577C7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4B8B5DD7C8B344A0864FDF0A37422ECF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED2000BF37C483CB9EAADCF4BA3ABD4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'blogualhmisEq05'
          slot-name: 'Production'
          package: ./public

          
